class FindQueueModel {
  int queueId;
  String queueNo;
  String fname;
  String lname;
  String sex;
  String dob;
  String queueDate;
  dynamic macaddress;
  dynamic std;
  dynamic groupId;
  int? ca1;
  int? ca2;
  int? ca3;
  int? ca4;
  int? ca5;
  int? ca6;
  int? ca7;
  int? ca8;
  int? ca9;
  int? ca10;
  int? ca11;
  int? ca12;
  int? ca13;
  int? ca14;
  int? ca15;
  dynamic ca16;
  String? idcardexpriry;
  int unitId;
  String age;
  int rangeId;
  dynamic startTime;
  dynamic endTime;
  dynamic startQueueNo;
  dynamic endQueueNo;
  String unitName;
  dynamic interviewDate;
  dynamic username;
  dynamic status;

  factory FindQueueModel.fromJson(Map<String, dynamic> json) => FindQueueModel(
        queueId: json['queue_id'],
        queueNo: json['queue_no'],
        fname: json['fname'],
        lname: json['lname'],
        sex: json['sex'],
        dob: json['dob'],
        queueDate: json['queue_date'],
        macaddress: json['macaddress'],
        std: json['std'],
        groupId: json['groupId'],
        ca1: json['ca1'],
        ca2: json['ca2'],
        ca3: json['ca3'],
        ca4: json['ca4'],
        ca5: json['ca5'],
        ca6: json['ca6'],
        ca7: json['ca7'],
        ca8: json['ca8'],
        ca9: json['ca9'],
        ca10: json['ca10'],
        ca11: json['ca11'],
        ca12: json['ca12'],
        ca13: json['ca13'],
        ca14: json['ca14'],
        ca15: json['ca15'],
        ca16: json['ca16'],
        idcardexpriry: json['idcardexpriry'],
        unitId: json['unit_id'],
        age: json['age'],
        rangeId: json['range_id'],
        startTime: json['start_time'],
        endTime: json['end_time'],
        startQueueNo: json['start_queue_no'],
        endQueueNo: json['end_queue_no'],
        unitName: json['unit_name'],
        interviewDate: json['interview_date'],
        username: json['username'],
        status: json['status'],
      );

  FindQueueModel({
    required this.queueId,
    required this.queueNo,
    required this.fname,
    required this.lname,
    required this.sex,
    required this.dob,
    required this.queueDate,
    required this.macaddress,
    required this.std,
    required this.groupId,
    required this.ca1,
    required this.ca2,
    required this.ca3,
    required this.ca4,
    required this.ca5,
    required this.ca6,
    required this.ca7,
    required this.ca8,
    required this.ca9,
    required this.ca10,
    required this.ca11,
    required this.ca12,
    required this.ca13,
    required this.ca14,
    required this.ca15,
    required this.ca16,
    required this.idcardexpriry,
    required this.unitId,
    required this.age,
    required this.rangeId,
    required this.startTime,
    required this.endTime,
    required this.startQueueNo,
    required this.endQueueNo,
    required this.unitName,
    required this.interviewDate,
    required this.username,
    required this.status,
  });
}
